### ISSUE TITLE
update_node function in FuzzyART

### ISSUE THREAD

**Issue by josephgarnier** [chen0040/java-adaptive-resonance-theory#1]
I think in **FuzzyART.java** you should overwrite `update_node` because it's not the same learning function in ART and FuzzyART.
In FuzzyART:
```java
    protected void update_node(double[] x, int j){
		double[] W_j = weights.get(j);
		for(int i=0; i < x.length; ++i){
			W_j[i] = (1 - beta) * W_j[i] + beta * Math.min(x[i], W_j[i]); // not W_j[i] * x[i]
		}
	}
```

**Comment by chen0040** [comment]
@JosephGarnier Many thanks for uncovering the issue, yes you are right the update_node should be overwritten in FuzzyART, I have now incorporated your changes into the version 1.0.6. Thank you!
